DROP TABLE IF EXISTS picture;
CREATE TABLE picture (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author INTEGER NOT NULL,
  release_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  filename TEXT NOT NULL,
  captation TEXT,
  printed INTEGER 
);

DROP TABLE IF EXISTS picture_pack;
CREATE TABLE picture_pack (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT NOT NULL,
);