DROP TABLE IF EXISTS photo;

CREATE TABLE photo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author INTEGER NOT NULL,
  release_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  filename TEXT NOT NULL,
  captation TEXT,
  printed INTEGER 
);